services:
  chainlit-demo:
    build: 
      context: ./chainlit
      dockerfile: Dockerfile.chainlit
    ports:
      - "8000:8000"
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8000
      - API_BASE_URL=https://govstack-api.think.ke
      - GOVSTACK_API_KEY=b689ccc1-d925-4c4e-871a-379fcd79f269
    env_file:
      - .env
    networks:
      - govstack-network

networks:
  govstack-network:
    external: true